# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628e51ca131ec9b1995962e29bb243000c857e63fffd2467ba186a18331903e35198b6933c3cadf059ba0f04e2b9edfc0e1500d57e9d1ffd32bb7a347e97744b

test:
  secret_key_base: 0a9d49a202cab7b42a620ed067031583ff1367da5811bc07943b16884803b7a0637599ebdeb1a776ff5eefffb34ef9010687ba4f6f04f2cd747e8626701c09f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
